### ISSUE TITLE
Not work create device with Android sdk cmdline-tools

### ISSUE THREAD

**Issue by Carnage78** [NovatecConsulting/fastlane-plugin-android_emulator#11]
https://github.com/NovatecConsulting/fastlane-plugin-android_emulator/blob/1f29947f01e64e33657f69f83c61fd07440b1529/lib/fastlane/plugin/android_emulator/actions/android_emulator_action.rb#L24

**Comment by m-ruhl** [comment]
Should be fixed with the newest version `1.2.1`
