### ISSUE TITLE
Failing to launch emulator - Android Studio 3.4 (Mac OS)

### ISSUE THREAD

**Issue by RDKeith** [NovatecConsulting/fastlane-plugin-android_emulator#5]
![Screen Shot 2019-04-18 at 1 01 30 AM](https://user-images.githubusercontent.com/11847958/56345823-81e75480-6175-11e9-8ca9-48152fc65f5e.png)

Note - this was performing without issue prior to updating Android Studio.

**Comment by m-ruhl** [comment]
Hey Keith,

I updated also to Android Studio 3.4, but not have any issues so far.
Your issue seems to be related with the avdmanager, can you run `avdmanager list avd` ?
Maybe something is broken in the Android-SDK.
